[project]
name = "21"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "pyqt6>=6.8.0",
    "z3-solver>=4.13.4.0",
]
